### ISSUE TITLE
Вопрос по заданию 4

### ISSUE THREAD

**Issue by BogdanVU** [chesdenis/net-courses#11]
В задании 4 требуется вывести свойства созданных экземпляров классов, при том, что часть свойств из автогенерируемого кода. Есть ли способ динамически учесть возможные изменения набора свойств класса, не использующий рефлексию?

**Comment by chesdenis** [comment]
Я думаю без рефлексии не получится, можно попробовать через атрибуты - но это тоже рефлексия. Как вариант поместить в tt файле эту функцию.
