### ISSUE TITLE
EF Example

### ISSUE THREAD

**Issue by BogdanVU** [chesdenis/net-courses#110]
У меня у одного вылетает ошибка при запуске примера по EntityFramework, который выложил Денис? Запускаю ORMExampleConsoleApp

**Comment by ivanleb** [comment]
а что за ошибка?

**Comment by BogdanVU** [comment]
При выполнении блока TablePerHierarchy возникает ошибка 
![default](https://user-images.githubusercontent.com/35866917/39398144-69e96cee-4b12-11e8-919c-0db804a8edea.png)

Часть TablePerType выполняется без ошибок.

В части TablePerConcreteClass  возникает ошибка
![default](https://user-images.githubusercontent.com/35866917/39398178-082d2292-4b13-11e8-9f30-24b597b4fae1.png)

**Comment by chesdenis** [comment]
Так и не получилось создать TablePerConcreteClass? Еще актуально?
