### ISSUE TITLE
Логгер+тесты, работа с контейнером

### ISSUE THREAD

**Issue by nikitanut** [chesdenis/net-courses#128]
1) Я правильно понимаю, что метод, завёрнутый в логгер, не сможет нормально проходить тесты, и его надо переписать? У меня этот метод

```
public void RegisterNewClient(Client client)
        {
            loggerService.RunWithExceptionLogging(() =>
            {
                dataContext.Add(client);
                dataContext.SaveChanges();
            }, isSilent: true);
        }
```

не проходит следующий тест:

```
[TestMethod]
        public void CanRegisterNewClient()
        {
            var client = new Client { Name = "Bill", Surname = "Black" };

            businessService.RegisterNewClient(client);

            Received.InOrder(() =>
            {
                dataContext.Received(1).Add(Arg.Any<Client>());
                dataContext.Received(1).SaveChanges();
            });
        }
```
Если я убираю логгер, то всё ок.

2. Здесь выбрасывается исключение **StructureMap.StructureMapConfigurationException: 'No default Instance is registered and cannot be automatically determined for type 'log4net.ILog''** при создании dealProducer:
```
var logger = LogManager.GetLogger("StockExchangeLogger");
Container container = new Container(_ =>
{
      _.For<ILoggerService>().Use<LoggerService>().Ctor<ILog>().Is(logger);
      _.For<IDealProducer>().Use<DealProducer>();
});
var loggerService = container.GetInstance<ILoggerService>();
var dealProducer = container.GetInstance<IDealProducer>();
```
Не знаю, как это исправить. Логгер в этом задании создаёт много проблем, либо я делаю что-то не так.
https://github.com/chesdenis/net-courses/commit/fe350c81170af86b0a8d9eb4e572ff11f66d37b9

**Comment by VoidSignal** [comment]
Добавь логгер в контейнер.
`For<ILog>().Use(LogManager.GetLogger("SampleLogger"));`
Конфигурацию контейнера, наверно, "правильнее" вынести в отдельный файл.

**Comment by nikitanut** [comment]
@VoidSignal спасибо, помогло.

**Comment by BogdanVU** [comment]
@nikitanut В твоей старой версии логгер передавался в конструктор бизнес сервиса? И в тестах ты его заменял на заглушку с помощью NSubstitute?

**Comment by VoidSignal** [comment]
@BogdanVU у меня сейчас всё так и есть [(1509103)](https://github.com/chesdenis/net-courses/commit/1509103d0d20b4de28c49dbfb5bf1eb6bb0c7295), и это не работает.

**Comment by BogdanVU** [comment]
@VoidSignal Когда ты делаешь 
```
this.loggerService = Substitute.For<ILoggerService>();
```
то у тебя создается заглушки для методов RunWithExceptionLogging, которые начинают ничего не делать. Поэтому внутри них не происходит вызовов ваших методов.

**Comment by VoidSignal** [comment]
@BogdanVU Есть способ задать поведение, при котором заглушки будут выполнять Action, который в них передали? Тогда нормально всё вроде должно быть. Я даже не знаю, как загуглить такое.

**Comment by BogdanVU** [comment]
@VoidSignal Ну ты можешь написать еще одну реализацию класса, которая по сути будет отличаться от обычного логгера отсутствием самого логирования, но логика подавления исключений будет той же. Затем в NSubstitute для ILoggerService использовать твой "новый" логгер. Может есть какой-то другой способ, но это первое, что пришло в голову.

**Comment by chesdenis** [comment]
не не, нужно именно сделать правильно заглушку :) Например вот так:  
`this.loggerService.When(l => l.RunWithExceptionLogging(Arg.Any<Action>())).Do(info => info.Arg<Action>().Invoke());`

Этим самым как раз вы и задаете такое поведение. чтобы вызывался метод внутри сервиса.

**Comment by VoidSignal** [comment]
@chesdenis Теперь тест проходит, спасибо.
