### ISSUE TITLE
Reviewing

### ISSUE THREAD

**Issue by nikitanut** [chesdenis/net-courses#28]
Should I click "Merge pull request" if I'm the second reviewer who approved changes? Or only @chesdenis  can merge branches?
![2018-04-02_23-24-40](https://user-images.githubusercontent.com/30297448/38214378-184911b8-36cd-11e8-8474-1fd2a7d5092e.png)

**Comment by chesdenis** [comment]
Anyone from reviewers and code owner as well can merge pull request. I'll do additional check in master also.
