### ISSUE TITLE
PULLREQUESTS 

### ISSUE THREAD

**Issue by KRTone** [chesdenis/net-courses#42]
Я указываю в качестве ревьюверов рандомно(или стараюсь затрагивать тех, кого не видел в ревьюверах других/своих реквестов или видел мало). Я один в таком положении? Может стоит как-то систематизировать это или [и так сойдет](https://i.ytimg.com/vi/mNH6REibyHU/hqdefault.jpg)?

**Comment by Gomerd** [comment]
я просто последовательно добавляю: сделал первое задание добавил первых двух из списка, сделал второе - следующих двоих

**Comment by KRTone** [comment]
Я к тому, просто получается кто-то вообще ничего не проверил, а кто-то две трети всех тасков
