### ISSUE TITLE
Задание с урока

### ISSUE THREAD

**Issue by AnnaMiky** [chesdenis/net-courses#6]
@chesdenis Подскажите, что-то такое надо было сделать в пятницу? Не уверена что правильно поняла
[Event.txt](https://github.com/chesdenis/net-courses/files/1866024/Event.txt)

**Comment by chesdenis** [comment]
Да, примерно похоже - но без прогресса выполнения. Но суть передана правильно. 4 апреля рассмотрим практическое задание по events - будет понятнее.
