### ISSUE TITLE
Function notation rules

### ISSUE THREAD

**Issue by BogdanVU** [chesdenis/net-courses#75]
Всегда ли можно реализацию функтора делать без return, т.е. x=>!x.IsValid вместо x=>{return !x.IsValid}?

**Comment by chesdenis** [comment]
приведи плиз свой фрагмент кода который не компилится

**Comment by BogdanVU** [comment]
@chesdenis Проблема была в объявление элементов листа функторов из задания 6.
Сейчас сделал исправление на 
var filter = new List<Func<int, bool>>() { x => x % 3 == 0, x =>  x % 5 == 0 };
Ошибок не возникло. Это я, скорее всего, просто напутал знаки препинания в объявлении элементов листа. Вопрос снимается)
